// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR6HGGLsT8-5tEQ5BkVYq1gox5UNB5-ho',
    appId: '1:272176787666:web:e085661a5094f25cf97d0b',
    messagingSenderId: '272176787666',
    projectId: 'magnetic-e6255',
    authDomain: 'magnetic-e6255.firebaseapp.com',
    storageBucket: 'magnetic-e6255.appspot.com',
    measurementId: 'G-6TX6VE4ZLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI9RulJKLD-VHMQ-KS8az1e1IBbEDKgWk',
    appId: '1:272176787666:android:9b76322d70fd90bef97d0b',
    messagingSenderId: '272176787666',
    projectId: 'magnetic-e6255',
    storageBucket: 'magnetic-e6255.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP_3WWUQ83RmNlobS5O4DHnrmaLjbvcDc',
    appId: '1:272176787666:ios:2a77ceb1be56abe7f97d0b',
    messagingSenderId: '272176787666',
    projectId: 'magnetic-e6255',
    storageBucket: 'magnetic-e6255.appspot.com',
    iosClientId: '272176787666-midqvt75gnaseh644dhls07emsi2nrs9.apps.googleusercontent.com',
    iosBundleId: 'com.example.magnetic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP_3WWUQ83RmNlobS5O4DHnrmaLjbvcDc',
    appId: '1:272176787666:ios:2a77ceb1be56abe7f97d0b',
    messagingSenderId: '272176787666',
    projectId: 'magnetic-e6255',
    storageBucket: 'magnetic-e6255.appspot.com',
    iosClientId: '272176787666-midqvt75gnaseh644dhls07emsi2nrs9.apps.googleusercontent.com',
    iosBundleId: 'com.example.magnetic',
  );
}
